"""Install a post-commit git hook that triggers codebase re-indexing.

Usage::

    python scripts/install_index_hook.py [repo_root]

If *repo_root* is omitted the current working directory is used.  The script
writes (or overwrites) ``.git/hooks/post-commit`` with a small shell script
that calls ``python -m tools.code_index_cli`` after every commit.
"""

from __future__ import annotations

import stat
import sys
from pathlib import Path

HOOK_SCRIPT = """\
#!/usr/bin/env sh
# Auto-generated by scripts/install_index_hook.py
# Re-index the codebase after every commit.
python -m tools.code_index_cli --root "$(git rev-parse --show-toplevel)" || true
"""


def install(repo_root: str | None = None) -> Path:
    """Install the post-commit hook and return the hook path."""
    root = Path(repo_root).resolve() if repo_root else Path.cwd()
    git_dir = root / ".git"
    if not git_dir.is_dir():
        raise FileNotFoundError(f"No .git directory found at {root}")

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    hook_path = hooks_dir / "post-commit"
    hook_path.write_text(HOOK_SCRIPT, encoding="utf-8")

    # Make executable
    current = hook_path.stat().st_mode
    hook_path.chmod(current | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    return hook_path


if __name__ == "__main__":
    root_arg = sys.argv[1] if len(sys.argv) > 1 else None
    path = install(root_arg)
    print(f"Installed post-commit hook at {path}")
